In [1]:
import numpy as np
import scipy as sp
from scipy import stats
import matplotlib.pyplot as plt

data2 = np.genfromtxt('/Users/bryanchia/Desktop/BootCamp2017/ProbSets/Econ/Wk4_StrEst/data/MacroSeries.txt', delimiter = ',')

c = data2[:,0]
k = data2[:,1]
w = data2[:,2]
r = data2[:,3]

Problem 2
==============

In [2]:
#Part A

def z_pdf(w, k, rho, alpha, mu, sigma):
    
    zpast = np.empty((len(w)))
    zvals = np.log(w) - np.log(1-alpha) - alpha * np.log(k)
    zpast[0] = mu
    zpast[1:] = zvals[:-1]
    mean = rho * zpast + (1- rho) * mu
    
    denom1 = (2 * sigma**2)
    if np.isclose(denom1, 0, atol = 1e-25):
        denom1 = 1e-24
    
    exponent = np.exp( - (zvals - mean)**2 / denom1 )
    exponent[np.isclose(exponent, np.zeros_like(exponent), atol = 1e-30)] = 1e-29
    
    denom2 = sigma * np.sqrt(2 * np.pi)
    if np.isclose(denom2, 0, atol = 1e-25):
        denom2 = 1e-24
    
    pdf_vals = (1/denom2) * exponent
    pdf_vals[np.isclose(pdf_vals, np.zeros_like(pdf_vals), atol = 1e-30)] = 1e-29
    
    return pdf_vals

def log_lik_znorm(w, k, rho, alpha, mu, sigma):
 
    pdf_vals = z_pdf(w, k, rho, alpha, mu, sigma)
    ln_pdf_vals = np.log(pdf_vals)
    log_lik_val = ln_pdf_vals.sum()
    
    return log_lik_val

def crit(params, *args):

    rho, alpha, mu, sigma = params
    w, k = args
    log_lik_val = log_lik_znorm(w, k, rho, alpha, mu, sigma)
    neg_log_lik_val = -log_lik_val
    #print (neg_log_lik_val)
    
    return neg_log_lik_val

import scipy.optimize as opt

alpha_init = 0.5
rho_init = 0
mu_init = 1
sig_init = 1
bnds = ((-1 + 1e-5, 1 - 1e-5),(1e-5, 1 - 1e-5),(1e-5, None),(1e-5, None))
params_init = np.array([rho_init, alpha_init, mu_init, sig_init])
mle_args = (w, k)
results = opt.minimize(crit, params_init, args= mle_args, method = 'L-BFGS-B', bounds = bnds)
rho_MLE, alpha_MLE, mu_MLE, sigma_MLE  = results.x
print("MLE results: ", "\nRho = ", rho_MLE, "\nAlpha = ", alpha_MLE, "\nMu = ", mu_MLE, "\nSigma = ", sigma_MLE)
print("Hessian = ", results.hess_inv.todense())

MLE results:  
Rho =  0.479873665481 
Alpha =  0.70202487959 
Mu =  6.25490684743 
Sigma =  0.0920448666888
Hessian =  [[  1.78762764e+02  -2.28097976e+02   2.80482586e+03   2.20535936e+01]
 [ -2.28097976e+02   3.22353938e+02  -3.96582559e+03  -3.16589719e+01]
 [  2.80482586e+03  -3.96582559e+03   4.87904974e+04   3.89519196e+02]
 [  2.20535936e+01  -3.16589719e+01   3.89519196e+02   3.11643617e+00]]


In [3]:
#Part B

def z2_pdf(r, k, rho, alpha, mu, sigma):
    
    zpast = np.empty((len(r)))
    zvals = np.log(r) - np.log(alpha) - (alpha - 1) * np.log(k)
    zpast[0] = mu
    zpast[1:] = zvals[:-1]
    mean = rho * zpast + (1- rho) * mu
    
    denom1 = (2 * sigma**2)
    if np.isclose(denom1, 0, atol = 1e-25):
        denom1 = 1e-24
    
    exponent = np.exp( - (zvals - mean)**2 / denom1 )
    exponent[np.isclose(exponent, np.zeros_like(exponent), atol = 1e-30)] = 1e-29
    
    denom2 = sigma * np.sqrt(2 * np.pi)
    if np.isclose(denom2, 0, atol = 1e-25):
        denom2 = 1e-24
    
    pdf_vals = (1/denom2) * exponent
    pdf_vals[np.isclose(pdf_vals, np.zeros_like(pdf_vals), atol = 1e-30)] = 1e-29
    
    return pdf_vals

def log_lik_znorm2(r, k, rho, alpha, mu, sigma):
 
    pdf_vals = z2_pdf(r, k, rho, alpha, mu, sigma)
    ln_pdf_vals = np.log(pdf_vals)
    log_lik_val = ln_pdf_vals.sum()
    
    return log_lik_val

def crit2(params, *args):

    rho, alpha, mu, sigma = params
    w, k = args
    log_lik_val = log_lik_znorm2(r, k, rho, alpha, mu, sigma)
    neg_log_lik_val = -log_lik_val
    #print (neg_log_lik_val)
    
    return neg_log_lik_val

import scipy.optimize as opt

alpha_init = 0.5
rho_init = 0
mu_init = 1
sig_init = 1 
bnds = ((-1 + 1e-5, 1 - 1e-5),(1e-5, 1 - 1e-5),(1e-5, None),(1e-5, None))
params_init2 = np.array([rho_init, alpha_init, mu_init, sig_init])
mle_args = (r, k)
results = opt.minimize(crit2, params_init2, args= mle_args, method = 'L-BFGS-B', bounds = bnds)
rho_MLE, alpha_MLE, mu_MLE, sigma_MLE  = results.x
print("MLE results: ", "\nRho = ", rho_MLE, "\nAlpha = ", alpha_MLE, "\nMu = ", mu_MLE, "\nSigma = ", sigma_MLE)
print("Hessian = ", results.hess_inv.todense())

MLE results:  
Rho =  0.479983436642 
Alpha =  0.70193268349 
Mu =  5.07676281408 
Sigma =  0.0920454824043
Hessian =  [[  4.61478907e+02  -5.36600638e+02   9.19425424e+03   3.32499713e+01]
 [ -5.36600638e+02   6.34599574e+02  -1.08733195e+04  -3.97688740e+01]
 [  9.19425424e+03  -1.08733195e+04   1.86305008e+05   6.81402282e+02]
 [  3.32499714e+01  -3.97688740e+01   6.81402282e+02   2.51080252e+00]]


In [5]:
#Part 3


def z3_pdf(z, zp, rho, alpha, mu, sigma):

    mean = rho * zp + (1- rho) * mu
    
    denom1 = (2 * sigma**2)
    if np.isclose(denom1, 0, atol = 1e-25):
        denom1 = 1e-24
    
    exponent = np.exp( - (z - mean)**2 / denom1 )
    
    denom2 = sigma * np.sqrt(2 * np.pi)
    if np.isclose(denom2, 0, atol = 1e-25):
        denom2 = 1e-24
    
    pdf_vals = (1/denom2) * exponent
    
    return pdf_vals

k = 7500000
r = 1
zp = 10
alpha = alpha_MLE

z = np.log(r) - np.log(alpha_MLE) - (alpha_MLE - 1) * np.log(k)
print(z)

z3 = lambda x: z3_pdf(x, zp, rho_MLE, alpha_MLE, mu_MLE, sigma_MLE)

(vals, err) = sp.integrate.quad(z3, z , np.inf )

print(vals)

5.07244666661
0.9999999999998865
