In [1]:
#Problem 1

import numpy as np

def dotproduct():
    
    mat1A = np.array([ [3, -1, 4],[1, 5, -9] ])
    mat1B = np.array([ [2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2, -3] ])
    product1 = np.dot(mat1A,mat1B)
    
    return product1

product1 = dotproduct()

print(product1)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


In [2]:
#Problem 2

import numpy as np

def matrixproduct():
    
    mat2 = np.array([ [3, 1, 4],[1, 5, 9],[-5, 3, 1] ])
    product2 = (-1)*mat2.dot(mat2).dot(mat2) + 9*np.dot(mat2,mat2) - 15*mat2
    
    return product2

product2 = matrixproduct()

print(product2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
#Problem 3

import numpy as np

def prob3():
    
    #Define matrices
    
    mat3A1 = np.ones((7,7))
    mat3A = np.triu(mat3A1)
    
    mat3B1 = np.full((7,7),-1)
    mat3B2 = np.tril(mat3B1)
    
    mat3B3 = np.full_like(mat3B1, 5)
    mat3B4 = np.triu(mat3B3)
    
    mat3B5 = np.diag([-5,-5,-5,-5,-5,-5,-5])
    
    mat3B = mat3B2 + mat3B4 + mat3B5
    
    #Calculate matrix product 
    
    product3 =  mat3A@mat3B@mat3A
    
    #Change data type
    
    product3 = product3.astype(np.int64)
    
    return product3

product3 = prob3()

print(product3)

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


In [9]:
#Problem 4

import numpy as np

def prob4(array):
      
    #Copy array
    copy = np.copy(array)
    
    #Do fancy indexing
    mask = copy < 0
    copy[mask] = 0
    
    return copy

#array1 is my test case here
array1 = np.array([-1, 1, 1, -1, -1, 0, 5])
copy = prob4(array1)

print(copy)

[0 1 1 0 0 0 5]


In [25]:
#Problem 5

import numpy as np

def prob5():
    
    #Define matrices 
    
    mat5A1 = np.arange(6)
    mat5A2 = mat5A1.reshape((3,2))
    mat5A = mat5A2.T
    
    mat5B1 = np.full((3,3),3)
    mat5B = np.tril(mat5B1)
    
    mat5C = np.diag([-2, -2, -2])
    
    mat022 = np.zeros((2, 2))
    mat032 = np.zeros((3, 2))
    mat023 = np.zeros((2, 3))
    mat033 = np.zeros((3, 3))
    
    I = np.identity(3)
    
    one = np.hstack((mat033, mat5A2, I ))
    two = np.hstack((mat5A, mat022, mat023))
    three = np.hstack((mat5B, mat032, mat5C))
    
    matrix5 = np.vstack((one, two, three))
    
    return matrix5

matrix5 = prob5()

print(matrix5)

[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


In [35]:
#Problem 6

import numpy as np

def prob6(array):
    
    copy = np.copy(array)
    copy = copy.astype(np.float64)
    
    sumvector = copy.sum(axis=1)
    sumvector1 = sumvector.reshape(3,1)
    print(sumvector1)
    
    matrix6 = copy/sumvector1
    
    return matrix6

#Test case
array6 = np.arange(9).reshape((3,3))

matrix6 = prob6(array6)
print(matrix6)

[[  3.]
 [ 12.]
 [ 21.]]
[[ 0.          0.33333333  0.66666667]
 [ 0.25        0.33333333  0.41666667]
 [ 0.28571429  0.33333333  0.38095238]]


In [10]:
#Problem 7 

import numpy as np 

grid = np.load("/Users/bryanchia/Desktop/BootCamp2017/Computation/Wk1_PyIntro/grid.npy") 

maxhor = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
#print(maxhor)

maxver = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
#print(maxver)

maxrightdiag = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1:,2:-1] * grid[3:,3:])
#print(maxrightdiag)

maxleftdiag = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1:,1:-2] * grid[3:,:-3])
#print(maxleftdiag)

array = np.array([maxhor, maxver, maxrightdiag, maxleftdiag])

maximum = np.max(array)
print(maximum)

70600674
